liip_imagine:
    filter_sets:
        produit_resize:
            filters:
                thumbnail:
                    size: [150, 150]   # Dimensions maximales pour la largeur et la hauteur
                    mode: outbound      # Garder les proportions tout en redimensionnant à la taille maximale
