<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container70hH0ul\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container70hH0ul/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container70hH0ul.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container70hH0ul\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container70hH0ul\App_KernelDevDebugContainer([
    'container.build_hash' => '70hH0ul',
    'container.build_id' => 'b74e87c1',
    'container.build_time' => 1746699779,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container70hH0ul');
