controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_atelier_delete_ajax:
    path: /atelierBack/atelier/delete
    controller: App\Controller\AtelierController::delete
    methods: GET

# config/routes.yaml
predict:
  path: /predict
  controller: App\Controller\PredictController::predict
#api_statistiques:
 #   path: /api/statistiques
  #  controller: App\Controller\StatistiquesController::statistiques
   # methods: [GET]

reserve_place:
    path: /reserve-place
    controller: App\Controller\SeatController::reservePlace

    
#some_endpoint:
 #   path: /some-endpoint
  #  controller: App\Controller\InterfaceController::someEndpointAction

#send_message:
#    path: /send-message
 #   controller: App\Controller\InterfaceController::sendMessage
  #  methods: POST

#fetch_messages:
 #   path: /fetch-messages
   # controller: App\Controller\InterfaceController::fetchMessages
   # methods: GET


connect_google:
    path: /connect/google
    controller: App\Controller\SecurityController::connectGoogle

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\SecurityController::connectGoogleCheck