controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_atelier_delete_ajax:
    path: /atelierBack/atelier/delete
    controller: App\Controller\AtelierController::delete
    methods: GET

# config/routes.yaml
predict:
  path: /predict
  controller: App\Controller\PredictController::predict
api_statistiques:
    path: /api/statistiques
    controller: App\Controller\StatistiquesController::statistiques
    methods: [GET]
