controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_atelier_delete_ajax:
    path: /atelierBack/atelier/delete
    controller: App\Controller\AtelierController::delete
    methods: GET
