parameters:
    uploads_directory: '%kernel.project_dir%/public/img/users'
    image_directory: '%kernel.project_dir%/public/img/stock'
    atelier_directory: '%kernel.project_dir%/public/img/atelier'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    twilio_sid: '%env(TWILIO_SID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # EmailMessageHandler service
    App\Service\EmailMessageHandler:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
        tags: ['messenger.message_handler']

    # WeatherService service
    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'

    # TwilioService service
    App\Service\TwilioService:
        arguments:
            $twilioSid: '%env(TWILIO_SID)%'
            $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    # ProduitListener event listener
    App\EventListener\ProduitListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
