parameters:
    uploads_directory: '%kernel.project_dir%/public/img/users'
    image_directory: '%kernel.project_dir%/public/img/stock'
    atelier_directory: '%kernel.project_dir%/public/img/atelier'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    twilio_sid: '%env(TWILIO_SID)%'
    face_recognition_script: '%kernel.project_dir%/python/recognize_faces.py'
    users_image_path: '%kernel.project_dir%/public/img/users'
    files_directory: '%kernel.project_dir%/public/img/files'
    # config/services.yaml
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'   # Secret key for server-side


    sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Produit
                repository: App\Repository\ProduitRepository



services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $pythonScriptPath: '%face_recognition_script%'
            $usersImagePath: '%users_image_path%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # EmailMessageHandler service
    App\Service\EmailMessageHandler:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
        tags: ['messenger.message_handler']

    # WeatherService service
    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'
    App\Service\NotificationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    


    # TwilioService service
    App\Service\TwilioService:
        arguments:
            $twilioSid: '%env(TWILIO_SID)%'
            $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    # ProduitListener event listener
    App\EventListener\ProduitListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'preUpdate' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


